/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 10 19:56:05 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.AssumptionViolatedException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AppendPairProgram_ESTest extends AppendPairProgram_ESTest_scaffolding {


public static void main(String[] args) throws Throwable {
test4();
}

  @Test(timeout = 4000)
  public static void test0()  throws Throwable  {
      int[] intArray0 = new int[2];
      List list0 = AppendPairProgram.listgen(intArray0);
      assertFalse(list0.isLengthOdd());
  }

  @Test(timeout = 4000)
  public static void test1()  throws Throwable  {
      AppendPairProgram appendPairProgram0 = new AppendPairProgram();
      int[] intArray0 = new int[9];
      List list0 = AppendPairProgram.listgen(intArray0);
      List list1 = list0.next;
      list1.next = list0;
      // Undeclared exception!
      appendPairProgram0.TestStudentSubmission(list1, (-993));
  }

  @Test(timeout = 4000)
  public static void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        AppendPairProgram.listgen((int[]) null);
        fail("Expecting exception: AssumptionViolatedException");
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
         verifyException("org.junit.Assume", e);
      }
  }

  @Test(timeout = 4000)
  public static void test3()  throws Throwable  {
      AppendPairProgram appendPairProgram0 = new AppendPairProgram();
      // Undeclared exception!
      try { 
        appendPairProgram0.TestStudentSubmission((List) null, 508);
        fail("Expecting exception: AssumptionViolatedException");
      
      } catch(AssumptionViolatedException e) {
         //
         // got: <false>, expected: is <true>
         //
         verifyException("org.junit.Assume", e);
      }
  }

  @Test(timeout = 4000)
  public static void test4()  throws Throwable  {
      AppendPairProgram appendPairProgram0 = new AppendPairProgram();
      int[] intArray0 = new int[0];
      List list0 = AppendPairProgram.listgen(intArray0);
      appendPairProgram0.TestStudentSubmission(list0, 0);
      // Undeclared exception!
      try { 
        appendPairProgram0.TestStudentSubmission(list0, 0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
